apiVersion: v1
kind: Service
metadata:
  name: contract-audit
  labels:
    app: contract-audit
spec:
  type: ClusterIP
  selector:
    app: contract-audit
  ports:
    - name: http
      port: 80
      targetPort: http
